<?php
/**
 * Layout helpers (header/footer)
 * -----------------------------
 * These functions output the shared page chrome: <head>, navigation and footer.
 *
 * NOTE:
 * - This project uses PHP files to render the UI (no .html files).
 * - Each page includes this file and calls render_header()/render_footer().
 */

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/functions.php';
require_once __DIR__ . '/auth.php';

/**
 * Render the standard HTML header and top navigation.
 *
 * @param string $title Page-specific title
 * @param bool $requireAuth If true, show the authenticated navigation
 * @return void
 */
function render_header($title, $requireAuth = false)
{
  $user = current_user();
  if ($requireAuth && !$user) {
    // If a page calls render_header(requireAuth=true), we ensure login is required.
    header('Location: ' . url('/login.php'));
    exit;
  }

  $flash = flash_get();

  // Everything below is plain HTML generated by PHP.
  // This still respects the user's "no .html files" requirement.
  ?>
  <!doctype html>
  <html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= e($title) ?> · <?= e(APP_NAME) ?></title>
    <link rel="stylesheet" href="<?= e(url('/assets/style.css')) ?>">
  </head>

  <body>
    <header class="topbar">
      <div class="container topbar__inner">
        <a class="brand" href="<?= e(url('/')) ?>"><?= e(APP_NAME) ?></a>

        <nav class="nav">
          <?php if ($user): ?>
            <a class="nav__link" href="<?= e(url('/dashboard.php')) ?>">Dashboard</a>
            <a class="nav__link" href="<?= e(url('/cars.php')) ?>">Cars</a>
            <a class="nav__link" href="<?= e(url('/teams.php')) ?>">Teams</a>
            <a class="nav__link" href="<?= e(url('/drivers.php')) ?>">Drivers</a>
            <a class="nav__link" href="<?= e(url('/stats.php')) ?>">Stats</a>
            <span class="nav__spacer"></span>
            <span class="nav__user">Signed in as <strong><?= e($user['name']) ?></strong></span>
            <a class="nav__link nav__link--danger" href="<?= e(url('/logout.php')) ?>">Logout</a>
          <?php else: ?>
            <a class="nav__link" href="<?= e(url('/login.php')) ?>">Login</a>
            <a class="nav__link nav__link--primary" href="<?= e(url('/register.php')) ?>">Register</a>
          <?php endif; ?>
        </nav>
      </div>
    </header>

    <main class="container">
      <?php if ($flash): ?>
        <div class="alert alert--<?= e($flash['type']) ?>">
          <?= e($flash['message']) ?>
        </div>
      <?php endif; ?>
      <?php
}

/**
 * Render the standard HTML footer.
 *
 * @return void
 */
function render_footer()
{
  ?>
    </main>

    <footer class="footer">
      <div class="container footer__inner">
        <div class="footer__muted">
          &copy; <?= e(date('Y')) ?> · Made with 🧠 by <a href="https://instagram.com/singhvijaypr">Vijay Pratap Singh</a>
        </div>
      </div>
    </footer>
  </body>

  </html>
  <?php
}

